apiVersion: v1
kind: ConfigMap
metadata:
  name: onepacerr
data:
  TZ: Australia/Sydney
  LOG_LEVEL: info
  LOG_OUTPUT: json

  PIPELINE_SKIP_VERIFY_PRESENT_FILES: "true"
  PIPELINE_SKIP_ORGANIZE_PRESENT_FILES: "true"
  PIPELINE_SKIP_UPDATE_METADATA_PRESENT_FILES: "false"
  PIPELINE_SKIP_DOWNLOADS: "true"
  PIPELINE_INCLUDE_SPECIALS: "true"
  PIPELINE_PREFER_EXTENDED: "true"
  PIPELINE_PREFER_ALTERNATE: "true"
  PIPELINE_SKIP_SUPPLEMENTS: "false"

  LIBRARY_MEDIA_SERVER: jellyfin
  LIBRARY_SERIES_NAME: One Pace
  LIBRARY_SERIES_FOLDER_NAME: One Pace
  LIBRARY_CREATE_SHOW_IF_NOT_FOUND: "true"
  LIBRARY_USE_HARDLINKS: "true"
  JELLYFIN_URL: http://jellyfin:8096
  JELLYFIN_LIBRARY_NAME: Anime

  TORRENT_CLIENT: qbittorrent
  TORRENT_URL: http://qbittorrent:8080
  TORRENT_CATEGORY: onepacerr
  TORRENT_CATEGORY_ONCE_COMPLETED: onepacerr-completed

  METADATA_LANGUAGE: en
  METADATA_POSTER_SET: default
