apiVersion: v1
kind: Service
metadata:
  name: onepacerr
  labels:
    app.kubernetes.io/name: onepacerr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: onepacerr
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
