repositories:
  - name: longhorn
    url: https://charts.longhorn.io

  - name: metallb
    url: https://metallb.github.io/metallb

  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: jameswynn
    url: http://jameswynn.github.io/helm-charts/
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.0

  # Load balancer
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.9

  # DNS blocking
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.27.0
    values:
      - ./values/pihole.values.yaml

  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.12.0
    values:
      - ./values/nginx-internal.values.yaml

  # Automatic DNS for Pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.7.2
    values:
      - ./values/externaldns.values.yaml

  # Secret management
  - name: sealed-secrets
    namespace: sealed-secrets
    chart: bitnami/sealed-secrets
    version: 2.5.4
    values:
      - ./values/sealedsecrets.values.yaml

  - name: homepage
    namespace: homepage-system
    chart: jameswynn/homepage
    version: 2.0.1
    values:
      - ./values/homepage.values.yaml
