apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
  namespace: jellyfin-media
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      anime:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: anime

        include:
          # Anime WEB-1080p
          - template: sonarr-quality-definition-anime
          - template: sonarr-v4-quality-profile-anime
          - template: sonarr-v4-custom-formats-anime

      series:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        include:
          # WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          # WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p

    radarr:
      movies:
        base_url: http://radarr:7878
        api_key: !secret RADARR_API_KEY

        quality_definition:
          type: movie

        include:
          - template: radarr-quality-definition-movie

          # WEB-1080p - doesn't really find many movies.
          - template: radarr-quality-profile-remux-web-1080p
          - template: radarr-custom-formats-remux-web-1080p

          # WEB-2160p - Prestige
          - template: radarr-quality-profile-remux-web-2160p
          - template: radarr-custom-formats-remux-web-2160p

          # Bluray + Web for mass media movies
          - template: radarr-quality-profile-hd-bluray-web
          - template: radarr-custom-formats-hd-bluray-web
