---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: configarr
  namespace: jellyfin-media
spec:
  encryptedData:
    secrets.yml: AgACr5ZnqMfKxYGmi0x7n4AUuoZWkTpxfZ/BmOdT3oSwlygmw+BDKYPbbzAiMjmAf56xfy5hv/guY3ClqEzX4wKE+P5HBcczjNXauK8/w7rduMIIbSKntI1C+uCJat9SDrNve72IuoPVcjAq1vp3g+WwmBAd1tOcNXMsFXoSseSLfRphDxqFGWdwQuPLvk6hSBNbBTl93SfsiOuSHpfOjwkDIf5NGie+fMGW3woaktoe+hVh3+hmzXb0xOPqXpjvWmCZhuVJLEjK39sJP+kfGL/Unk8GsffEZm2LglVVETfETCU2xlVmkQR2AP7gnaWCCkrO6gplkf1vB9GtYKCBYDtcnsAGWSkEjGoQCeYgmPh/+dHZwFyIff2cU4SzhX8BR20Iy1cMZicvwE8ehRY7BQOOnfMiPZyVPxpjE9GjkgQYsrHVi0p1qaW8gCTFSLlQ1k0hTFBW9aKDOkl8B8jMgaV53yZCZK5Y0Az9ylVvBdRz++DTXL6ojEB2aCpOl1B3vfoF4uyANGdCWFrNxJ6miCAXGaIjI5e4Skkx50igJzexZIrOG6H+75gZvvBX2SlKKPRaw9vkpWaJ4lZk2vo3M+1tlJWZoMz9Uw5Efj91rv97yffiHjle1PFcazxqIzOosmnS3Le4LidUD4WLlX7dpXdCPQPQv8i8rbPywXSfxsJEO6/uBMPdPUBUNycWqFuBhbWDdCl5c3KVSPx6w5J+QECcNG4/Otgw/gN1PhJxogeEgntUUsd72twltBTDdqXvmZkXnLCWrQuGVwElixjS2CdNXaLX7ov502FyC+F4i604igHuH9BbkfCtZ0gnNMWq/OTr
  template:
    metadata:
      name: configarr
      namespace: jellyfin-media
    type: Opaque
