apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - pihole.yaml
  - metallb.yaml
  - ingress-nginx.yaml
  - external-dns.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
