apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actualbudget
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: actualbudget
      targetRevision: 1.8.4
      helm:
        releaseName: actualbudget
        valueFiles:
          - $values/apps/services/values/actualbudget.values.yaml
    - repoURL: https://github.com/Sheeplet1/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: budget-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
