apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://rubxkube.github.io/charts/
      chart: linkding
      targetRevision: 1.1.20
      helm:
        releaseName: linkding
        valueFiles:
          - $values/apps/services/values/linkding.values.yaml
    - repoURL: https://github.com/Sheeplet1/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkding-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
