apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: jellyfin-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  resources:
    requests:
      storage: 1.5Ti
