apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configarr
  namespace: argocd
spec:
  project: default
  source:
    path: apps/media/configarr
    repoURL: https://github.com/Sheeplet1/homelab
    targetRevision: main
  destination:
    namespace: jellyfin-media
    server: "https://kubernetes.default.svc"
