apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://lib42.github.io/charts
      chart: flaresolverr
      targetRevision: 2.0.0
      helm:
        releaseName: flaresolverr
        valueFiles:
          - $values/apps/media/values/flaresolverr.values.yaml
    - repoURL: https://github.com/Sheeplet1/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin-media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
