apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - sonarr.yaml
  - radarr.yaml
  - jellyfin.yaml
  - jellyseerr.yaml
  - qbittorrent.yaml
  - flaresolverr.yaml
  - prowlarr.yaml
  - configarr.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
