apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.gabe565.com
      chart: qbittorrent
      targetRevision: 0.4.0
      helm:
        releaseName: qbittorrent
        valueFiles:
          - $values/apps/media/values/qbittorrent.values.yaml
    - repoURL: https://github.com/Sheeplet1/homelab
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin-media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
