ingress:
  main:
    enabled: true
    className: nginx-internal
    hosts:
      - host: reader.sheeplet.com
        paths:
          - path: /
            pathType: Prefix

postgresql:
  enabled: true
  auth:
    database: miniflux
    postgresPassword: miniflux
    username: miniflux
    password: miniflux
  persistence:
    enabled: true
    storageClass: longhorn
    size: 8Gi
