apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.gabe565.com
      chart: miniflux
      targetRevision: 0.9.2
      helm:
        releaseName: miniflux
        valueFiles:
          - $values/apps/miniflux/miniflux.values.yaml
    - repoURL: https://github.com/Sheeplet1/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: miniflux-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
