service:
  main:
    ports:
      http:
        port: 8191

ingress:
  main:
    enabled: true
    className: nginx-internal
    hosts:
      - host: flaresolverr.sheeplet.com
        paths:
          - path: /
            pathType: Prefix
